services:
  mysql:
    image: mysql:8.4.3
    restart: unless-stopped
    volumes:
      - ./.dockervolumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: root
